apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      containers:
      - name: node-exporter-test
        image: prom/node-exporter
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
          limits:
            cpu: "4000m"
            memory: "512Mi"
